language: node_js
node_js:
  - "stable"
env:
  - NODE_ENV="development"
services:
  - mongodb
addons:
  sonarcloud:
    organization: default
    token:
      secure: "0d6446b57419652ac731cb706833f7b0f7a548db"

script: npm run build